use crate::adapters::atomic::{atomic_write, backup_file, FileLock};
use crate::domain::{AgentRulesTargetResult, TargetKind};
use crate::error::{AppError, AppResult};
use crate::paths::{
    claude_rules_path, resolve_codex_home, resolve_pi_agent_dir, resolve_prime_agent_dir,
};
use std::fs;
use std::path::{Path, PathBuf};

/// 托管块标记。用 HTML 注释是因为它在 Markdown 渲染里不可见，同时又是纯文本行，
/// 便于用户人肉定位与 grep。前缀与 MCP 的 `xiaobai_` 命名空间同源。
const RULE_BEGIN: &str = "<!-- xiaobai-switch:begin global-rules -->";
const RULE_END: &str = "<!-- xiaobai-switch:end global-rules -->";
/// 写在块里的固定提示。它是落进目标文件的文件内容（可能跨语言切换后残留），
/// 不是 UI 文案，所以这里是 i18n 约定的有意例外：固定双语，不随界面语言变。
const RULE_NOTICE: &str = "<!-- Generated by XiaoBaiSwitch Plus · 由 XiaoBaiSwitch Plus 生成，请勿在此块内手工编辑 -->";

const BOM: &str = "\u{feff}";

fn render_block(body: &str) -> String {
    let trimmed = body.trim_end_matches(['\n', '\r']);
    format!("{RULE_BEGIN}\n{RULE_NOTICE}\n{trimmed}\n{RULE_END}")
}

fn validate_body(body: &str) -> AppResult<()> {
    if body.contains(RULE_BEGIN) || body.contains(RULE_END) || body.contains(RULE_NOTICE) {
        return Err(AppError::new(
            "validation_failed",
            "the rules text must not contain the XiaoBaiSwitch managed-block markers",
        ));
    }
    Ok(())
}

/// 落库前的校验：标记字面量写进数据库后无法可靠界定托管块，必须在保存前拦下。
pub fn validate_body_for_storage(body: &str) -> AppResult<()> {
    validate_body(body)
}

/// 删除全部托管块并返回剩余内容与删除的块数。
///
/// - 出现 BEGIN 但之后没有配对的 END：报错（文件被手工改坏，不能猜着改）。
/// - 只有 END 没有 BEGIN：不报错，按用户自己的内容原样保留。
fn strip_blocks(text: &str) -> AppResult<(String, usize)> {
    let mut out = String::with_capacity(text.len());
    let mut removed = 0;
    let mut rest = text;
    while let Some(begin_at) = rest.find(RULE_BEGIN) {
        out.push_str(&rest[..begin_at]);
        let after_begin = &rest[begin_at..];
        let Some(end_rel) = after_begin.find(RULE_END) else {
            return Err(AppError::new(
                "invalid_config",
                "the managed block has a start marker but no end marker",
            ));
        };
        removed += 1;
        rest = &after_begin[end_rel + RULE_END.len()..];
    }
    out.push_str(rest);
    Ok((out, removed))
}

/// 把剩余内容收拾成「块外内容 + 恰好一个末尾换行」。
fn tidy_remainder(text: &str) -> String {
    let trimmed = text.trim_end_matches(['\n', '\r']);
    if trimmed.trim().is_empty() {
        return String::new();
    }
    format!("{trimmed}\n")
}

/// 计算写入后的完整文件内容。`None` 表示要求清掉托管块。
///
/// 返回新内容与是否真的发生了变化；内容不变时调用方必须跳过写盘与备份，
/// 否则每次保存都会无谓地触碰客户端文件、污染备份目录。
fn apply_block(text: &str, block: Option<&str>) -> AppResult<(String, bool)> {
    let (remainder, removed) = strip_blocks(text)?;
    // 要求清理、而文件里本来就没有托管块：原样返回，绝不去顺带整理用户的空行。
    if block.is_none() && removed == 0 {
        return Ok((text.to_string(), false));
    }
    let next = match block {
        Some(block) => {
            let base = tidy_remainder(&remainder);
            if base.is_empty() {
                format!("{block}\n")
            } else {
                // 尾部已有换行时 tidy_remainder 保证只留一个，这里再补一个空行分隔。
                format!("{base}\n{block}\n")
            }
        }
        None => tidy_remainder(&remainder),
    };
    let changed = next != text;
    Ok((next, changed))
}

struct Loaded {
    text: String,
    had_bom: bool,
    existed: bool,
}

fn read_target(path: &Path) -> AppResult<Loaded> {
    if path.is_dir() {
        return Err(AppError::new(
            "invalid_config",
            format!("{} is a directory, not a file", path.display()),
        ));
    }
    if !path.exists() {
        return Ok(Loaded {
            text: String::new(),
            had_bom: false,
            existed: false,
        });
    }
    let bytes = fs::read(path)?;
    let text = String::from_utf8(bytes).map_err(|_| {
        AppError::new(
            "invalid_config",
            format!("{} is not valid UTF-8", path.display()),
        )
    })?;
    Ok(Loaded {
        had_bom: text.starts_with(BOM),
        text,
        existed: true,
    })
}

/// 把一段正文写进某个目标文件，或（`body = None`）把托管块清理掉。
pub fn apply_to_path(
    path: &Path,
    body: Option<&str>,
    backup_root: &Path,
) -> AppResult<AgentRulesTargetResult> {
    let label = path.display().to_string();
    if let Some(body) = body {
        validate_body(body)?;
    }
    let block = body.map(render_block);

    // 与目标 CLI（以及本应用其他适配器）对同一个文件的读写互斥。
    let _lock = FileLock::acquire(path)?;
    let loaded = read_target(path)?;
    let (next, changed) = apply_block(&loaded.text, block.as_deref())?;

    if !changed {
        return Ok(AgentRulesTargetResult {
            target: TargetKind::ClaudeCode,
            ok: true,
            path: label,
            changed: false,
            backup_paths: Vec::new(),
            message: "no change".to_string(),
        });
    }

    let mut backup_paths = Vec::new();
    if loaded.existed {
        backup_paths.push(backup_file(path, backup_root)?.display().to_string());
    }

    let empty = next.trim().is_empty();
    if empty && loaded.existed {
        // 整个文件都是本应用写的：删掉它，否则 Pi/Prime 会把空的 AGENTS.md
        // 当成优先文件，反而遮蔽用户自己的 CLAUDE.md。
        fs::remove_file(path)?;
    } else if !next.is_empty() {
        let payload = if loaded.had_bom {
            format!("{BOM}{next}")
        } else {
            next.clone()
        };
        atomic_write(path, payload.as_bytes(), false)?;
    }

    Ok(AgentRulesTargetResult {
        target: TargetKind::ClaudeCode,
        ok: true,
        path: label,
        changed: true,
        backup_paths,
        message: if body.is_some() {
            "applied".to_string()
        } else {
            "cleared".to_string()
        },
    })
}

/// Codex 的 `AGENTS.override.md` 会整体遮蔽 `AGENTS.md`：只检测并回报给 UI，不改写它。
fn codex_override_shadow(codex_home: &Path) -> Option<String> {
    let override_path = codex_home.join("AGENTS.override.md");
    override_path
        .is_file()
        .then(|| override_path.display().to_string())
}

/// Pi/Prime 的目标文件选择：已有 `AGENTS.md` 用它；否则已有 `CLAUDE.md` 就追加进
/// `CLAUDE.md`（新建 `AGENTS.md` 会让用户手写的 `CLAUDE.md` 被整体遮蔽）；都没有则新建
/// `AGENTS.md`（两个 CLI 文档里的首选文件名）。
fn agents_or_claude(agent_dir: &Path) -> PathBuf {
    let agents = agent_dir.join("AGENTS.md");
    if agents.is_file() {
        return agents;
    }
    let claude = agent_dir.join("CLAUDE.md");
    if claude.is_file() {
        return claude;
    }
    agents
}

fn target_path(target: TargetKind, overrides: &TargetOverrides) -> AppResult<PathBuf> {
    Ok(match target {
        TargetKind::ClaudeCode => claude_rules_path(overrides.claude_home.as_deref())?,
        TargetKind::Codex => resolve_codex_home(overrides.codex_home.as_deref())?.join("AGENTS.md"),
        TargetKind::Pi => agents_or_claude(&resolve_pi_agent_dir(overrides.pi_agent_dir.as_deref())?),
        TargetKind::Prime => {
            agents_or_claude(&resolve_prime_agent_dir(overrides.prime_agent_dir.as_deref())?)
        }
    })
}

/// 四个目标的用户级 override 设置（与 `commands/apply.rs` 用的是同一批字段）。
#[derive(Debug, Default, Clone)]
pub struct TargetOverrides {
    pub claude_home: Option<String>,
    pub codex_home: Option<String>,
    pub pi_agent_dir: Option<String>,
    pub prime_agent_dir: Option<String>,
}

pub fn target_paths(overrides: &TargetOverrides) -> AppResult<Vec<(TargetKind, PathBuf)>> {
    [
        TargetKind::ClaudeCode,
        TargetKind::Codex,
        TargetKind::Pi,
        TargetKind::Prime,
    ]
    .into_iter()
    .map(|target| Ok((target, target_path(target, overrides)?)))
    .collect()
}

pub fn codex_shadow(overrides: &TargetOverrides) -> AppResult<Option<String>> {
    Ok(codex_override_shadow(&resolve_codex_home(
        overrides.codex_home.as_deref(),
    )?))
}

/// 把一个目标写盘（或清理），并把结果里的 `target` 字段修正为该目标。
pub fn apply_to_target(
    target: TargetKind,
    body: Option<&str>,
    overrides: &TargetOverrides,
    backup_root: &Path,
) -> AppResult<AgentRulesTargetResult> {
    let path = target_path(target, overrides)?;
    let mut result = apply_to_path(&path, body, backup_root)?;
    result.target = target;
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn read(path: &Path) -> String {
        fs::read_to_string(path).unwrap()
    }

    fn backup_root(dir: &Path) -> PathBuf {
        dir.join("backups")
    }

    // ---------- 纯函数 ----------

    #[test]
    fn render_block_wraps_body_and_normalizes_trailing_newlines() {
        let block = render_block("# 约束\n- 说中文\n\n\n");
        assert!(block.starts_with(RULE_BEGIN));
        assert!(block.ends_with(RULE_END));
        assert!(block.contains("- 说中文"));
        assert!(!block.contains("\n\n\n"), "trailing blank lines are dropped");
        assert_eq!(block.matches(RULE_BEGIN).count(), 1);
        assert_eq!(block.matches(RULE_END).count(), 1);
    }

    #[test]
    fn validate_body_rejects_marker_literals() {
        assert!(validate_body("正常内容").is_ok());
        for body in [
            RULE_BEGIN,
            RULE_END,
            RULE_NOTICE,
            "前缀 <!-- xiaobai-switch:begin global-rules --> 后缀",
        ] {
            let error = validate_body(body).unwrap_err();
            assert_eq!(error.code(), "validation_failed");
        }
    }

    #[test]
    fn strip_blocks_removes_managed_blocks_and_keeps_user_text() {
        let text = format!("用户内容\n\n{}\n\n用户尾部\n", render_block("正文"));
        let (remainder, removed) = strip_blocks(&text).unwrap();
        assert_eq!(removed, 1);
        assert!(!remainder.contains(RULE_BEGIN));
        assert!(remainder.contains("用户内容"));
        assert!(remainder.contains("用户尾部"));
    }

    #[test]
    fn strip_blocks_errors_when_begin_has_no_end() {
        let error = strip_blocks(&format!("用户内容\n{RULE_BEGIN}\n正文\n")).unwrap_err();
        assert_eq!(error.code(), "invalid_config");
    }

    #[test]
    fn strip_blocks_keeps_stray_end_marker() {
        // 只有 END 没有 BEGIN：无法判断是谁写的，按用户内容原样保留。
        let text = format!("用户内容\n{RULE_END}\n");
        let (remainder, removed) = strip_blocks(text.as_str()).unwrap();
        assert_eq!(removed, 0);
        assert_eq!(remainder, text);
    }

    #[test]
    fn apply_block_is_idempotent() {
        let block = render_block("正文");
        let (once, changed) = apply_block("用户内容\n", Some(&block)).unwrap();
        assert!(changed);
        let (twice, changed_again) = apply_block(&once, Some(&block)).unwrap();
        assert_eq!(once, twice);
        assert!(!changed_again, "re-saving identical rules must be a no-op");
    }

    #[test]
    fn apply_block_separates_user_text_with_exactly_one_blank_line() {
        for user in ["用户内容", "用户内容\n", "用户内容\n\n\n"] {
            let (next, _) = apply_block(user, Some(&render_block("正文"))).unwrap();
            assert!(
                next.starts_with("用户内容\n\n"),
                "expected one blank line separator, got {:?}",
                next
            );
        }
    }

    #[test]
    fn apply_block_collapses_multiple_blocks() {
        let text = format!(
            "{}\n\n中间用户内容\n\n{}\n",
            render_block("第一份"),
            render_block("第二份")
        );
        let (next, changed) = apply_block(&text, Some(&render_block("唯一一份"))).unwrap();
        assert!(changed);
        assert_eq!(next.matches(RULE_BEGIN).count(), 1);
        assert!(next.contains("中间用户内容"));
        assert!(!next.contains("第一份"));
        assert!(!next.contains("第二份"));
        assert!(next.contains("唯一一份"));
    }

    #[test]
    fn apply_block_none_clears_only_the_managed_block() {
        // 托管块位于文件中间（只可能是用户手工搬过去的）。移除后忠实保留用户原本的
        // 空行，不做内部空行整理——碰得越少越安全，Markdown 渲染也不受多余空行影响。
        let text = format!("# 用户的文件\n\n{}\n\n用户结尾\n", render_block("正文"));
        let (next, changed) = apply_block(&text, None).unwrap();
        assert!(changed);
        assert!(!next.contains(RULE_BEGIN));
        assert!(!next.contains("正文"), "the managed body must be gone");
        assert!(next.contains("# 用户的文件"));
        assert!(next.contains("用户结尾"));
        assert!(next.ends_with('\n'));
    }

    #[test]
    fn apply_block_none_empties_an_all_managed_file() {
        let text = format!("{}\n", render_block("正文"));
        let (next, _) = apply_block(&text, None).unwrap();
        assert_eq!(next, "");
    }

    #[test]
    fn clearing_a_file_without_any_block_is_a_pure_no_op() {
        // 回归：清理路径曾经会把用户的尾部空行一并归一，导致「本来就没事可做」时
        // 仍然改写用户文件。现在必须原样退回。
        for text in ["用户内容\n\n\n", "用户内容", "\n\n", "用户内容\r\n\r\n"] {
            let (next, changed) = apply_block(text, None).unwrap();
            assert_eq!(next, text, "user file must be returned byte-identical");
            assert!(!changed, "clearing with no managed block must report no change");
        }
    }

    // ---------- 文件级 ----------

    #[test]
    fn creates_file_with_only_the_block() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        let out = apply_to_path(&path, Some("# 全局约束\n"), &backup_root(dir.path())).unwrap();
        assert!(out.changed);
        assert!(out.backup_paths.is_empty(), "new file has nothing to back up");
        let text = read(&path);
        assert!(text.starts_with(RULE_BEGIN));
        assert!(text.contains("# 全局约束"));
        assert_eq!(text.matches(RULE_BEGIN).count(), 1);
    }

    #[test]
    fn preserves_user_content_bom_and_exact_bytes() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("AGENTS.md");
        // 用户内容：BOM + 无末尾换行 + 含标题与代码块。
        let user = "\u{feff}# 我的约定\n\n```sh\necho hi\n```";
        fs::write(&path, user).unwrap();

        let out = apply_to_path(&path, Some("新增约束"), &backup_root(dir.path())).unwrap();
        assert!(out.changed);
        assert_eq!(out.backup_paths.len(), 1, "existing file must be backed up");

        let text = read(&path);
        assert!(text.starts_with('\u{feff}'), "BOM must survive");
        assert!(text.contains(user.trim_start_matches('\u{feff}')));
        let block_at = text.find(RULE_BEGIN).unwrap();
        assert!(text[..block_at].trim_end().ends_with("```"));
        assert!(text.contains("新增约束"));
    }

    #[test]
    fn replacing_changes_only_the_block_and_keeps_user_text() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::write(&path, "# 用户内容\n").unwrap();
        apply_to_path(&path, Some("第一版"), &backup_root(dir.path())).unwrap();
        apply_to_path(&path, Some("第二版"), &backup_root(dir.path())).unwrap();

        let text = read(&path);
        assert!(text.starts_with("# 用户内容\n\n"));
        assert!(text.contains("第二版"));
        assert!(!text.contains("第一版"));
        assert_eq!(text.matches(RULE_BEGIN).count(), 1);
    }

    #[test]
    fn reapply_with_same_body_does_not_touch_the_file() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap();
        let out = apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap();
        assert!(!out.changed);
        assert!(out.backup_paths.is_empty(), "no-op must not create backups");
        assert!(!dir.path().join("backups").exists());
    }

    #[test]
    fn clearing_removes_block_and_deletes_a_fully_managed_file() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("AGENTS.md");
        apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap();
        assert!(path.exists());

        let out = apply_to_path(&path, None, &backup_root(dir.path())).unwrap();
        assert!(out.changed);
        assert!(!path.exists(), "a file we created entirely must be removed");
    }

    #[test]
    fn clearing_keeps_user_file() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::write(&path, "# 用户内容\n").unwrap();
        apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap();

        apply_to_path(&path, None, &backup_root(dir.path())).unwrap();
        assert_eq!(read(&path), "# 用户内容\n");
    }

    #[test]
    fn clearing_when_no_file_exists_is_a_no_op() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("AGENTS.md");
        let out = apply_to_path(&path, None, &backup_root(dir.path())).unwrap();
        assert!(!out.changed);
        assert!(!path.exists());
        assert!(!dir.path().join("backups").exists());
    }

    #[test]
    fn unterminated_block_fails_without_touching_the_file() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        let broken = format!("# 用户内容\n\n{RULE_BEGIN}\n少了结束标记\n");
        fs::write(&path, &broken).unwrap();

        let error = apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap_err();
        assert_eq!(error.code(), "invalid_config");
        assert_eq!(read(&path), broken, "file must be left byte-identical");
    }

    #[test]
    fn directory_in_place_of_file_reports_error() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::create_dir(&path).unwrap();
        let error = apply_to_path(&path, Some("正文"), &backup_root(dir.path())).unwrap_err();
        assert_eq!(error.code(), "invalid_config");
    }

    #[test]
    fn body_with_marker_literal_is_rejected_before_writing() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("CLAUDE.md");
        let error =
            apply_to_path(&path, Some(RULE_BEGIN), &backup_root(dir.path())).unwrap_err();
        assert_eq!(error.code(), "validation_failed");
        assert!(!path.exists());
    }

    // ---------- 路径选择 ----------

    #[test]
    fn pi_and_prime_prefer_agents_md_then_fall_back_to_claude_md() {
        let dir = tempdir().unwrap();
        let empty = dir.path().join("empty");
        fs::create_dir(&empty).unwrap();
        assert_eq!(agents_or_claude(&empty), empty.join("AGENTS.md"));

        let claude_only = dir.path().join("claude-only");
        fs::create_dir(&claude_only).unwrap();
        fs::write(claude_only.join("CLAUDE.md"), "# 用户自己写的\n").unwrap();
        assert_eq!(
            agents_or_claude(&claude_only),
            claude_only.join("CLAUDE.md"),
            "must not shadow the user's own CLAUDE.md by creating AGENTS.md"
        );

        let both = dir.path().join("both");
        fs::create_dir(&both).unwrap();
        fs::write(both.join("CLAUDE.md"), "用户\n").unwrap();
        fs::write(both.join("AGENTS.md"), "用户\n").unwrap();
        assert_eq!(agents_or_claude(&both), both.join("AGENTS.md"));
    }

    #[test]
    fn claude_path_follows_config_dir_and_override() {
        let overrides = TargetOverrides {
            claude_home: Some("/tmp/custom-claude".to_string()),
            ..Default::default()
        };
        let path = target_path(TargetKind::ClaudeCode, &overrides).unwrap();
        assert_eq!(path, PathBuf::from("/tmp/custom-claude/CLAUDE.md"));
    }

    #[test]
    fn codex_shadow_reports_override_file() {
        let dir = tempdir().unwrap();
        let overrides = TargetOverrides {
            codex_home: Some(dir.path().display().to_string()),
            ..Default::default()
        };
        assert!(codex_shadow(&overrides).unwrap().is_none());

        let override_path = dir.path().join("AGENTS.override.md");
        fs::write(&override_path, "# 遮蔽文件\n").unwrap();
        assert_eq!(
            codex_shadow(&overrides).unwrap().as_deref(),
            Some(override_path.display().to_string().as_str())
        );
    }

    #[test]
    fn target_paths_returns_all_in_display_order() {
        let overrides = TargetOverrides {
            claude_home: Some("/tmp/c".into()),
            codex_home: Some("/tmp/x".into()),
            pi_agent_dir: Some("/tmp/p".into()),
            prime_agent_dir: Some("/tmp/r".into()),
        };
        let paths = target_paths(&overrides).unwrap();
        assert_eq!(
            paths.iter().map(|(t, _)| *t).collect::<Vec<_>>(),
            vec![
                TargetKind::ClaudeCode,
                TargetKind::Codex,
                TargetKind::Pi,
                TargetKind::Prime
            ]
        );
        assert_eq!(paths[0].1, PathBuf::from("/tmp/c/CLAUDE.md"));
        assert_eq!(paths[1].1, PathBuf::from("/tmp/x/AGENTS.md"));
        assert_eq!(paths[2].1, PathBuf::from("/tmp/p/AGENTS.md"));
        assert_eq!(paths[3].1, PathBuf::from("/tmp/r/AGENTS.md"));
    }

    #[test]
    fn full_apply_then_clear_cycle_per_target() {
        let dir = tempdir().unwrap();
        let overrides = TargetOverrides {
            claude_home: Some(dir.path().join("claude").display().to_string()),
            codex_home: Some(dir.path().join("codex").display().to_string()),
            pi_agent_dir: Some(dir.path().join("pi").display().to_string()),
            prime_agent_dir: Some(dir.path().join("prime").display().to_string()),
        };
        let root = backup_root(dir.path());

        for target in [
            TargetKind::ClaudeCode,
            TargetKind::Codex,
            TargetKind::Pi,
            TargetKind::Prime,
        ] {
            let out = apply_to_target(target, Some("全局约束"), &overrides, &root).unwrap();
            assert!(out.ok, "{target:?} apply failed");
            assert_eq!(out.target, target);
            let text = read(Path::new(&out.path));
            assert!(text.contains("全局约束"), "{target:?} body missing");
            assert_eq!(text.matches(RULE_BEGIN).count(), 1);
        }
        assert!(dir.path().join("claude").join("CLAUDE.md").is_file());
        assert!(dir.path().join("codex").join("AGENTS.md").is_file());
        assert!(dir.path().join("pi").join("AGENTS.md").is_file());
        assert!(dir.path().join("prime").join("AGENTS.md").is_file());

        for target in [
            TargetKind::ClaudeCode,
            TargetKind::Codex,
            TargetKind::Pi,
            TargetKind::Prime,
        ] {
            let out = apply_to_target(target, None, &overrides, &root).unwrap();
            assert!(out.ok);
            assert!(!Path::new(&out.path).exists(), "{target:?} file should be gone");
        }
    }
}
